In [4]:
import numpy as np

In [ ]:
A=np.arange(1,13).reshape(3,4)
print(A)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [ ]:
B=np.linspace(13,19,4).reshape(2,2)
print(B)


[[13. 15.]
 [17. 19.]]


In [ ]:
C=np.array([22,33,88,36,14,39,56,3]).reshape(2,2,2)#Changes needs saving in another variable
print(C)

[[[22 33]
  [88 36]]

 [[14 39]
  [56  3]]]


In [ ]:
D=np.array([2,3,4,5,6,7,8,9])
D.resize(2,2,2,)#Changes the shape of original array
print(D)

[[[2 3]
  [4 5]]

 [[6 7]
  [8 9]]]


In [ ]:
a=np.array([5,13,19,6,8])
b=np.array([7,10,12,16,25])
c=a-b
print(c)

[ -2   3   7 -10 -17]


In [ ]:
A=np.array([26,29,20,37,2])
B=np.array([4,8,9,25,18])
c=A+B
print(c)

[30 37 29 62 20]


In [ ]:
#Matrix Multiplication
a=np.array([2,6,8,3,6]).reshape(1,5)
b=np.array([1,4,6,7,8]).reshape(5,1)
print(a)
print(b)
c=a@b
print(c)

[[2 6 8 3 6]]
[[1]
 [4]
 [6]
 [7]
 [8]]
[[143]]


In [ ]:
#Matrix multiplication
a=np.array([2,6,8,3,6]).reshape(1,5)
b=np.array([1,4,6,7,8]).reshape(5,1)
print(a)
print(b)
c=a.dot(b)
print(c)

[[2 6 8 3 6]]
[[1]
 [4]
 [6]
 [7]
 [8]]
[[143]]


In [ ]:
#max & min works only for numeric data types like integer and float
a=np.array([2,6,18,19,35])
print(a.max())
print(a.min())

35
2


In [ ]:
a=np.array([18,19,16,20,45,28]).reshape(3,2)
print(a)
print(a.max(axis=0))#column wise bigger number
print(a.max(axis=1))#row wise bigger number

[[18 19]
 [16 20]
 [45 28]]
[45 28]
[19 20 45]


In [ ]:
a=np.array([18,19,16,20,45,28]).reshape(3,2)
print(a)
print(a.min(axis=0))#column wise lower number
print(a.min(axis=1))#row wise lower number

[[18 19]
 [16 20]
 [45 28]]
[16 19]
[18 16 28]


In [ ]:
#joining arrays vertically
a=np.array([15,9,20,19]).reshape(2,2)
b=np.array([3,8,19,29]).reshape(2,2)
print(a)
print(b)
print(np.vstack((a,b)))

[[15  9]
 [20 19]]
[[ 3  8]
 [19 29]]
[[15  9]
 [20 19]
 [ 3  8]
 [19 29]]


In [ ]:
#joining arrays horizontally
a=np.array([15,9,20,19]).reshape(2,2)
b=np.array([3,8,19,29]).reshape(2,2)
print(a)
print(b)
print(np.hstack((a,b)))

[[15  9]
 [20 19]]
[[ 3  8]
 [19 29]]
[[15  9  3  8]
 [20 19 19 29]]


In [ ]:
a=np.array([15,9,20,19]).reshape(2,2)
b=np.array([3,8,19,29]).reshape(2,2)
print(a)
print(b)
print(np.stack((a,b),axis=0))

[[15  9]
 [20 19]]
[[ 3  8]
 [19 29]]
[[[15  9]
  [20 19]]

 [[ 3  8]
  [19 29]]]


In [ ]:
a=np.array([15,9,20,19]).reshape(2,2)
b=np.array([3,8,19,29]).reshape(2,2)
print(a)
print(b)
print(np.stack((a,b),axis=1))

[[15  9]
 [20 19]]
[[ 3  8]
 [19 29]]
[[[15  9]
  [ 3  8]]

 [[20 19]
  [19 29]]]


In [ ]:
A=np.arange(30).reshape(2,3,5)
print(A)
print("After dstack")
print(np.dstack(A))#no.of rows-->no.of groups
#no.of colums in every group - no.of group

[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]]

 [[15 16 17 18 19]
  [20 21 22 23 24]
  [25 26 27 28 29]]]
After dstack
[[[ 0 15]
  [ 1 16]
  [ 2 17]
  [ 3 18]
  [ 4 19]]

 [[ 5 20]
  [ 6 21]
  [ 7 22]
  [ 8 23]
  [ 9 24]]

 [[10 25]
  [11 26]
  [12 27]
  [13 28]
  [14 29]]]


In [ ]:
#Splitting arrays
A=np.arange(18).reshape(6,3)
print(A)
print(np.vsplit(A,3))

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]
 [15 16 17]]
[array([[0, 1, 2],
       [3, 4, 5]]), array([[ 6,  7,  8],
       [ 9, 10, 11]]), array([[12, 13, 14],
       [15, 16, 17]])]


In [ ]:
A=np.arange(18).reshape(6,3)
print(A)
print(np.vsplit(A,(2,5)))

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]
 [15 16 17]]
[array([[0, 1, 2],
       [3, 4, 5]]), array([[ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]]), array([[15, 16, 17]])]


In [ ]:
A=np.arange(18).reshape(6,3)
print(A)
print(np.vsplit(A,(2,3)))

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]
 [15 16 17]]
[array([[0, 1, 2],
       [3, 4, 5]]), array([[6, 7, 8]]), array([[ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17]])]


In [ ]:
A=np.arange(18).reshape(6,3)
print(A)
print(np.hsplit(A,(2,5)))

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]
 [15 16 17]]
[array([[ 0,  1],
       [ 3,  4],
       [ 6,  7],
       [ 9, 10],
       [12, 13],
       [15, 16]]), array([[ 2],
       [ 5],
       [ 8],
       [11],
       [14],
       [17]]), array([], shape=(6, 0), dtype=int64)]


In [ ]:
A=np.arange(18).reshape(3,6)
print(A)
print(np.hsplit(A,(2,5)))

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]]
[array([[ 0,  1],
       [ 6,  7],
       [12, 13]]), array([[ 2,  3,  4],
       [ 8,  9, 10],
       [14, 15, 16]]), array([[ 5],
       [11],
       [17]])]


In [ ]:
a=np.array([5,24,18,9]).reshape(2,2)
print(a)
print(a.argmax())

[[ 5 24]
 [18  9]]
1


In [ ]:
a=np.array([5,24,18,9]).reshape(2,2)
print(a)
print(a.argmax(axis=0))

[[ 5 24]
 [18  9]]
[1 0]


In [ ]:
a=np.array([5,24,18,9]).reshape(2,2)
print(a)
print(a.argmin())

[[ 5 24]
 [18  9]]
0


STATISTICS

In [ ]:
#Mean,Median,std,variance
A=[24,3,56,42,12]
print("Mean:",np.mean(A))
print("Median:",np.median(A))
print("Variance:",np.var(A))
print("Standard deviation:",np.std(A))

Mean: 27.4
Median: 24.0
Variance: 375.03999999999996
Standard deviation: 19.365949499056327


TRIGONOMETRY

In [ ]:
#PI value
print(np.pi)
print(a)#radians
print(np.rad2deg(a))#converts radians to degree

3.141592653589793
[[ 5 24]
 [18  9]]
[[ 286.47889757 1375.09870831]
 [1031.32403124  515.66201562]]


In [ ]:
#Radians to degree conevrsion
A=np.array([np.pi/4,np.pi/3,np.pi/2,np.pi])
print(np.rad2deg(A))#converts radians to degree

[ 45.  60.  90. 180.]


In [ ]:
#Degree to radians conversion
r=np.array([30,45,60,90,120,180])
c=np.deg2rad(r)
print(c)

[0.52359878 0.78539816 1.04719755 1.57079633 2.0943951  3.14159265]


In [ ]:
np.sin(r)

array([-0.98803162,  0.85090352, -0.30481062,  0.89399666,  0.58061118,
       -0.80115264])

In [ ]:
np.cos(r)

array([ 0.15425145,  0.52532199, -0.95241298, -0.44807362,  0.81418097,
       -0.59846007])

In [ ]:
np.tan(r)

array([-6.4053312 ,  1.61977519,  0.32004039, -1.99520041,  0.71312301,
        1.33869021])

SEARCHING

In [ ]:
A=np.array([32,2,4,5,21,8])
print(np.where(A==8))

(array([5]),)


In [ ]:
A=np.array([32,2,4,5,21,8])
print(np.where(A>8))

(array([0, 4]),)


In [8]:
A=np.array([32,2,4,5,21,8])
print(np.searchsorted(A,4))

2


In [11]:
A=np.array([5,8,74,14])
B=np.array([50,7,88,1])
print("Sum: ",np.add(A,B))
print("Difference:",np.subtract(A,B))
print("Product:",np.multiply(A,B))
print("Quotient:",np.divide(A,B))
print("Remainder:",np.mod(A,B))
print(np.divmod(A,B))

Sum:  [ 55  15 162  15]
Difference: [-45   1 -14  13]
Product: [ 250   56 6512   14]
Quotient: [ 0.1         1.14285714  0.84090909 14.        ]
Remainder: [ 5  1 74  0]
(array([ 0,  1,  0, 14]), array([ 5,  1, 74,  0]))


In [12]:
A=np.array([5,8,74,14])
print(np.sort(A))

[ 5  8 14 74]


SET FUNCTIONS


In [13]:
A=np.array([5,8,74,14])
B=np.array([50,7,88,1])
print(np.union1d(A,B))

[ 1  5  7  8 14 50 74 88]


In [14]:
A=np.array([5,8,74,14])
B=np.array([50,7,88,1])
print(np.setdiff1d(A,B))

[ 5  8 14 74]


In [16]:
A=np.array([5,8,74,14])
B=np.array([50,8,88,1])
print(np.intersect1d(A,B))

[8]


ROUNDING

In [17]:
a=np.trunc([2.0983,-6.9182])
print(a)

[ 2. -6.]


In [18]:
a=np.fix([2.0983,-6.9182])
print(a)

[ 2. -6.]


In [20]:
a=np.around(2.0983,2)
print(a)

2.1


In [22]:
a=np.floor([2.0983,-6.9182])
print(a)

[ 2. -7.]


In [23]:
a=np.ceil([2.0983,-6.9182])
print(a)

[ 3. -6.]


MORE FUNCTIONS

In [27]:
#Comulative Sum
a=np.array([9,3,4,12,5,3])
print(np.cumsum(a))

[ 9 12 16 28 33 36]


In [28]:
#Comulative Product
a=np.array([9,3,4,12,5,3])
print(np.cumprod(a))

[    9    27   108  1296  6480 19440]


In [31]:
#LCM & GCD
print(np.lcm(25,50))
print(np.gcd(35,90))

50
5


In [32]:
#LCM & GCD for mutiple elements
a=np.array([9,3,4,12,5,3])
print("LCM:",np.lcm.reduce(a))
print("GCD:",np.gcd.reduce(a))

LCM: 180
GCD: 1


In [33]:
a=np.array([[1,2],[3,4]])
print(np.linalg.inv(a))

[[-2.   1. ]
 [ 1.5 -0.5]]


In [34]:
from numpy import random as rdm

In [36]:
a=rd.rand()#limit-0 to 0.99
print(a)

0.9723504086666298


In [38]:
a=rd.randint(4)#limit -0 to 4
print(a)


3


In [40]:
a=rd.randint(40,size=(3,3))#Limit with shape
print(a)

[[15 32 14]
 [ 8 35 34]
 [20 34 21]]


In [42]:
A=np.array([1,2,3])
B=np.array([4,5,6])
print(np.inner(A,B))

32


In [43]:
A=np.array([1,2,3])
B=np.array([4,5,6])
print(np.outer(A,B))

[[ 4  5  6]
 [ 8 10 12]
 [12 15 18]]


In [44]:
A=np.array([1,2,3])
B=np.array([4,5,6])
print(np.cross(A,B))

[-3  6 -3]
